spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/capstone
    username: postgres
    password: riya
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
server:
  port: 8079

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8789/eureka/
